#pragma once

#define SIMPLEENGINE_VERSION_MAJOR 0
#define SIMPLEENGINE_VERSION_MINOR 2
#define SIMPLEENGINE_VERSION_PATCH 0
#define SIMPLEENGINE_VERSION_STRING "0.2.0"
#define SIMPLEENGINE_GIT_HASH "705965e"
#define SIMPLEENGINE_BUILD_TYPE "RelWithDebInfo"
